version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    networks:
      - search_engine
    restart: always
    volumes:
      - data01:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    
  tika:
    image: apache/tika:1.24.1-full
    networks: 
      - search_engine
    ports:
        - 9998:9998


volumes:
  data01: 
    driver: local

    
networks:
  search_engine:
